# Generated by Django 4.1.5 on 2023-01-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end',
            field=models.DateField(default='Present'),
        ),
    ]
