# Generated by Django 4.1.5 on 2023-02-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_prolanguages_technologies_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='pro_languages',
            field=models.ManyToManyField(to='resume.prolanguages'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='technologies',
            field=models.ManyToManyField(to='resume.technologies'),
        ),
    ]
